export type ProjectCategory = "business" | "client" | "finance" | "management" | "productivity" | "demo" | "other";

export type ProjectType = "web-app" | "mobile" | "business-website" | "ecommerce" | "package";

export type ProjectIcon = "bookmark" | "wallet" | "folder-up" | "scissors";

export type FeatureIcon = "list" | "file" | "chart" | "download" | "phone" | "qr" | "truck" | "card";

export type ProjectFeature = {
    icon: FeatureIcon;
    title: string;
    /** Short line for the homepage card */
    short: string;
    /** Longer line for the projects page */
    text: string;
};

export type Project = {
    slug: string;
    title: string;
    year: number;
    stack: string[];
    /** Short stack line for small cards */
    stackShort: string;
    /** Homepage tagline - keep to ~2 lines */
    description: string;
    /** What the product does */
    overview: string;
    /** What you built / the result */
    contribution: string;
    type: ProjectType;
    /** Logo image, shown instead of the mark */
    logo?: string;
    /** Initials shown in the project mark (used when there is no logo or icon) */
    mark?: string;
    icon?: ProjectIcon;
    /** Mark background colour */
    color: string;
    /** Live URL - omit when discontinued / not public */
    url?: string;
    /** Link label on small cards, e.g. "Visit site" or "Play it" */
    linkLabel?: string;
    /** Overrides the pill worked out from url/category. Omit for the default */
    status?: "live" | "private" | "in-progress" | "closed" | "deprecated";
    /** Built for a client (vs personal / product) */
    client?: boolean;
    sort: number;
    showOnHome: boolean;
    /** Large card on the projects page */
    featured?: boolean;
    /** "What's inside" list for featured cards */
    features?: ProjectFeature[];
    /** Colours of the "What's inside" panel */
    panel?: { background: string; border: string; accent: string };
    category: ProjectCategory;
};

export const typeLabel: Record<ProjectType, string> = {
    "web-app": "Web app",
    mobile: "Mobile",
    "business-website": "Business website",
    ecommerce: "Ecommerce",
    package: "npm package",
};

export const categoryLabel: Record<ProjectCategory, string> = {
    business: "Businesses I run",
    client: "Client work",
    finance: "Finance",
    productivity: "Productivity",
    management: "Management",
    demo: "Demos",
    other: "Experiments",
};

/** Singular label used in card meta lines, e.g. "Experiment · 2021" */
export const categoryMetaLabel: Record<ProjectCategory, string> = {
    business: "My business",
    client: "Client",
    finance: "Finance",
    productivity: "Productivity",
    management: "Management",
    demo: "Demo",
    other: "Experiment",
};

export const projects: Project[] = [
    {
        slug: "simple-trackr",
        logo: "/projects/logos/simple-trackr.svg",
        title: "Simple Trackr",
        year: 2026,
        stack: ["Next.js", "React", "Supabase", "Tailwind CSS", "Stripe"],
        stackShort: "Next.js · Supabase · Stripe",
        description:
            "Expense, income and invoice tracking for freelancers. Log every transaction, turn offers into branded invoices, and see the month in one dashboard.",
        overview:
            "Expense, income and invoice tracking for freelancers - log every transaction, turn offers into invoices, send branded invoices, and see the numbers in one dashboard.",
        contribution:
            "Built for my own freelance work first: transactions, offers, invoices, reports and CSV export - in one place instead of several files.",
        type: "web-app",
        mark: "ST",
        color: "#16284D",
        url: "https://simple-trackr.com",
        sort: 0,
        showOnHome: true,
        featured: true,
        panel: { background: "#F5F7FB", border: "#DCE1EB", accent: "#16284D" },
        features: [
            {
                icon: "list",
                title: "Transactions",
                short: "Income and expenses, categorised in one list.",
                text: "Log income and expenses and keep them categorised in one list.",
            },
            {
                icon: "file",
                title: "Offers → invoices",
                short: "Turn an accepted offer into a branded invoice.",
                text: "Turn an accepted offer into a branded invoice and send it.",
            },
            {
                icon: "chart",
                title: "Dashboard & reports",
                short: "See income, costs and net for any period.",
                text: "See income, costs and net for any period at a glance.",
            },
            {
                icon: "download",
                title: "CSV export",
                short: "Hand clean data to your accountant.",
                text: "Hand clean data to your accountant at year end.",
            },
        ],
        category: "finance",
    },
    // ── Businesses I run ──
    {
        slug: "handwerker-netz",
        logo: "/projects/logos/handwerker-netz.svg",
        title: "Handwerker Netz",
        year: 2026,
        stack: ["Next.js", "React", "next-intl", "Tailwind CSS"],
        stackShort: "Next.js · DE / EN",
        description: "Handyman service in Vienna. 95%+ of its clients come from the website and Google Maps.",
        overview:
            "A Vienna handyman business - furniture assembly, wall mounting and smart home installation, at a fixed price agreed before the job.",
        contribution:
            "The bilingual website (German and English) with a page for each service, quote requests with photos, and the Google Business Profile. I still improve it every week.",
        type: "business-website",
        mark: "HN",
        color: "#16284D",
        url: "https://handwerker-netz.at",
        sort: 1,
        showOnHome: false,
        category: "business",
    },
    {
        slug: "ideal-credit-system",
        logo: "/projects/logos/ideal-credit.svg",
        title: "Ideal Credit Management",
        year: 2026,
        stack: ["Next.js", "React", "Supabase", "Tailwind CSS"],
        stackShort: "Next.js · Supabase",
        description: "The internal system a consumer credit company runs on every day.",
        overview: "Loans, clients, payments, income and expenses for a consumer credit company in Moldova, in one place.",
        contribution: "Built the whole system and moved the data over from the old setup. Live and used by the team every day - a private app with no public access.",
        type: "web-app",
        mark: "IC",
        color: "#127A6F",
        status: "private",
        sort: 2,
        showOnHome: false,
        category: "business",
    },
    {
        slug: "ideal-credit-website",
        logo: "/projects/logos/ideal-credit.svg",
        title: "Ideal Credit website",
        year: 2022,
        stack: ["Next.js", "React", "MDX", "Tailwind CSS"],
        stackShort: "Next.js · MDX",
        description: "Website for a consumer credit company in Moldova, with loan calculators and articles.",
        overview: "The public website of Ideal Credit, a consumer credit company I co-founded.",
        contribution: "Built in 2022 and rebuilt since. Loan pages, calculators and articles, kept up to date.",
        type: "business-website",
        mark: "IC",
        color: "#127A6F",
        url: "https://idealcredit.md",
        sort: 3,
        showOnHome: false,
        category: "business",
    },

    // ── Client work ──
    {
        slug: "vino-vistara",
        title: "Vino Vistara",
        year: 2025,
        stack: ["Shopify", "Liquid"],
        stackShort: "Shopify · Horizon theme",
        description: "Shopify wine store, built on the Horizon theme.",
        overview: "An online wine store on Shopify.",
        contribution: "Set up the store and customised the Horizon theme.",
        type: "ecommerce",
        logo: "/projects/logos/vino-vistara.png",
        mark: "VV",
        color: "#7A2E3B",
        url: "https://vinovistara.com",
        client: true,
        sort: 10,
        showOnHome: false,
        category: "client",
    },
    {
        slug: "postu-bau",
        logo: "/projects/logos/postu-bau.svg",
        title: "Postu Bau",
        year: 2026,
        stack: ["Next.js", "React", "next-intl", "Storyblok", "Tailwind CSS"],
        stackShort: "Next.js · Storyblok · DE / EN",
        description: "Website for a building company in Austria - new builds, renovation and restoration.",
        overview: "Postu Bau GmbH is a master builder (Baumeister) working across Austria.",
        contribution: "Bilingual website (German and English) with project pages and a CMS, so the team can add projects on their own.",
        type: "business-website",
        mark: "PB",
        color: "#A2471A",
        url: "https://postu-bau.com",
        client: true,
        sort: 11,
        showOnHome: false,
        category: "client",
    },
    {
        slug: "balance-and-buddy",
        logo: "/projects/logos/balance-and-buddy.svg",
        title: "Balance & Buddy",
        year: 2026,
        stack: ["Next.js", "React", "Tailwind CSS"],
        stackShort: "Next.js · Tailwind",
        description: "Website for a premium athleisure boutique in Baden, Austria.",
        overview: "A local clothing boutique in Baden bei Wien.",
        contribution: "Designed and built the website.",
        type: "business-website",
        mark: "BB",
        color: "#3F434A",
        url: "https://balanceandbuddy.at",
        client: true,
        sort: 12,
        showOnHome: false,
        category: "client",
    },
    {
        slug: "lisa-tonge-solicitors",
        logo: "/projects/logos/lisa-tonge-solicitors.svg",
        title: "Lisa Tonge Solicitors",
        year: 2025,
        stack: ["Next.js", "React", "Tailwind CSS"],
        stackShort: "Next.js · Tailwind",
        description: "Website for a solicitor in Worsley, Manchester - conveyancing, wills and power of attorney.",
        overview: "A solicitor's practice in Worsley, Manchester (UK).",
        contribution: "Designed and built the website.",
        type: "business-website",
        mark: "LT",
        color: "#16284D",
        url: "https://lisatongesolicitors.com",
        client: true,
        sort: 13,
        showOnHome: false,
        category: "client",
    },
    {
        slug: "pompa-de-caldura",
        title: "Q-Term heat pumps",
        year: 2022,
        stack: ["Nuxt.js", "Vue.js", "Tailwind CSS"],
        stackShort: "Nuxt · Tailwind",
        description: "Website for a heat pump seller in Moldova - heating, hot water and cooling.",
        overview: "Q-Term sells and installs heat pumps for homes in Moldova.",
        contribution: "Designed and built the business website.",
        type: "business-website",
        mark: "QT",
        color: "#127A6F",
        url: "https://pompadecaldura.md",
        client: true,
        sort: 15,
        showOnHome: false,
        category: "client",
    },

    {
        slug: "jak-construction",
        logo: "/projects/logos/jak-construction.png",
        title: "JAK Construction",
        year: 2022,
        stack: ["WordPress", "Divi"],
        stackShort: "WordPress · Divi",
        description: "Website for a UK construction company - from small projects and kitchens to new builds.",
        overview:
            "A UK construction company: kitchen and bathroom design, renovations, new homes and barn conversions, with its own designers and architects.",
        contribution: "Designed and built the WordPress website.",
        type: "business-website",
        mark: "JAK",
        color: "#3F434A",
        url: "https://jakconstruction.co.uk",
        client: true,
        sort: 16,
        showOnHome: false,
        category: "client",
    },

    // ── My own apps & experiments ──
    {
        slug: "1food-menu",
        logo: "/projects/logos/1food-menu.svg",
        title: "1FoodMenu",
        year: 2022,
        stack: ["Next.js", "React", "Supabase", "Tailwind CSS", "Stripe"],
        stackShort: "Next.js · Supabase · Stripe",
        description: "Digital menus for restaurants and food trucks - a live page and QR code, updated from your phone.",
        overview:
            "A live digital menu for restaurants and food trucks - photos, prices, hours and a QR code. Update from your phone; guests open it in the browser, no app needed.",
        contribution:
            "I build and run it as my own product: menu editor, public menu pages, QR codes, restaurant and food-truck modes, and Stripe billing. Free to start.",
        type: "web-app",
        mark: "1F",
        color: "#C8551E",
        url: "https://1food.menu",
        sort: 20,
        showOnHome: false,
        featured: true,
        panel: { background: "#FBF5EF", border: "#EADFD4", accent: "#A2471A" },
        features: [
            {
                icon: "phone",
                title: "Edit from your phone",
                short: "Change prices, photos and hours in seconds.",
                text: "Change prices, photos and hours in seconds - the menu updates live.",
            },
            {
                icon: "qr",
                title: "QR code included",
                short: "Guests scan and open the menu in the browser.",
                text: "Guests scan and open the menu in the browser - no app needed.",
            },
            {
                icon: "truck",
                title: "Restaurants & food trucks",
                short: "Modes for a fixed restaurant and a food truck.",
                text: "Separate modes for a fixed restaurant and a food truck.",
            },
            {
                icon: "card",
                title: "Free to start",
                short: "Paid plans handled with Stripe billing.",
                text: "Paid plans handled with Stripe billing when you need more.",
            },
        ],
        category: "productivity",
    },
    {
        slug: "bookmark-manager",
        logo: "/projects/logos/bookmark-manager.svg",
        title: "Bookmark Manager",
        year: 2022,
        stack: ["Vue.js", "Tailwind CSS", "Firebase"],
        stackShort: "Vue.js · Tailwind · Firebase",
        description: "Save and organize links with tags and notes - synced across devices.",
        overview:
            "A dedicated place to save links with tags and notes, then find them again without digging through browser folders.",
        contribution: "Firebase sync, tag filtering, search, and bulk import from browser export files.",
        type: "web-app",
        icon: "bookmark",
        color: "#127A6F",
        url: "https://bookmarks-manager.online/",
        sort: 22,
        showOnHome: false,
        category: "productivity",
    },
    {
        slug: "saver-wallet",
        logo: "/projects/logos/saver-wallet.svg",
        title: "Saver Wallet",
        year: 2022,
        stack: ["Vue.js", "Tailwind CSS"],
        stackShort: "Vue.js · Tailwind · PWA",
        description: "Loyalty, membership and gift cards in one PWA - saved locally, no account needed.",
        overview: "Loyalty, membership and gift cards stored digitally, one tap away at checkout - no account needed.",
        contribution: "an installable PWA end to end - local storage, simple card UI, no backend or signup.",
        type: "web-app",
        icon: "wallet",
        color: "#7A5E6E",
        url: "https://saver-wallet.netlify.app/",
        sort: 23,
        showOnHome: false,
        category: "finance",
    },
    {
        slug: "bunny-cdn-manager",
        logo: "/projects/logos/bunny-cdn-manager.svg",
        title: "Bunny CDN Manager",
        year: 2023,
        stack: ["Vue.js", "Tailwind CSS"],
        stackShort: "Vue.js · Tailwind · Bunny API",
        description: "A cleaner Bunny CDN assets manager - uploads, folders, bulk delete, and image previews.",
        overview: "A faster layout for Bunny CDN storage zones - uploads, browsing and cleanup of assets in one clean view.",
        contribution: "a Vue UI on Bunny’s API with folders, drag-and-drop uploads, bulk delete and image previews.",
        type: "web-app",
        icon: "folder-up",
        color: "#A2471A",
        url: "https://bunny-cdn.netlify.app/",
        sort: 24,
        showOnHome: false,
        category: "management",
    },
    {
        slug: "rock-paper-scissors",
        logo: "/projects/logos/rock-paper-scissors.svg",
        title: "Rock Paper Scissors",
        year: 2025,
        stack: ["Next.js", "React", "Firebase"],
        stackShort: "Next.js · Firebase",
        description: "The easiest and simplest Rock Paper Scissors game online. Multiplayer - send a link and play with friends.",
        overview: "The easiest and simplest Rock Paper Scissors game online. Multiplayer - create a game, share the link and play in real time.",
        contribution: "Rebuilt in Next.js and Firebase. The first version was Vue and Appwrite.",
        type: "web-app",
        icon: "scissors",
        color: "#7A5E6E",
        url: "https://rps-game.online/",
        linkLabel: "Play it",
        status: "live",
        sort: 30,
        showOnHome: false,
        category: "other",
    },
    {
        // closed - merged into 1FoodMenu
        slug: "food-trucks-near-me",
        logo: "/projects/logos/food-trucks-near-me.png",
        title: "Food Trucks Near Me",
        year: 2024,
        stack: ["Nuxt.js", "Vue.js", "Supabase", "Storyblok"],
        stackShort: "Nuxt · Supabase",
        description: "A directory of food trucks - find trucks nearby, see menus and locations.",
        overview: "A directory site plus an app where food truck owners manage their listing.",
        contribution: "Built the public directory and the owner app, with Supabase for data and maps for locations. Closed now - merged into 1FoodMenu.",
        type: "web-app",
        mark: "FT",
        color: "#A2471A",
        status: "closed",
        sort: 21,
        showOnHome: false,
        category: "other",
    },
    {
        // closed - calculator-online.md no longer resolves
        slug: "calculator-online",
        logo: "/projects/logos/calculator-online.svg",
        title: "Calculator Online",
        year: 2024,
        stack: ["Next.js", "React", "Tailwind CSS"],
        stackShort: "Next.js · Tailwind",
        description: "Calculators for Moldova: gross to net salary, car import tax, VAT, percentages and dates.",
        overview: "Everyday calculators built around Moldovan tax rules, in Romanian.",
        contribution: "Built in Nuxt in 2024, rebuilt in Next.js in 2025. Closed now.",
        type: "web-app",
        mark: "CO",
        color: "#16284D",
        sort: 25,
        showOnHome: false,
        category: "finance",
    },
    {
        // closed - stripe-analytics.com no longer resolves
        slug: "stripe-analytics",
        logo: "/projects/logos/stripe-analytics.svg",
        title: "Stripe Analytics",
        year: 2024,
        stack: ["Nuxt.js", "Vue.js", "Firebase", "ApexCharts"],
        stackShort: "Nuxt · Firebase · Charts",
        description: "Sales reports and charts for businesses that sell with Stripe.",
        overview: "Connects to a Stripe account and shows revenue, customers and trends in charts.",
        contribution: "Built the app end to end: Stripe connection, reports and charts. Closed now.",
        type: "web-app",
        mark: "SA",
        color: "#5B4FD6",
        sort: 26,
        showOnHome: false,
        category: "finance",
    },
    {
        // private
        slug: "jobs-calendar",
        logo: "/projects/logos/jobs-calendar.svg",
        title: "Jobs Calendar",
        year: 2026,
        stack: ["Next.js", "React", "Firebase"],
        stackShort: "Next.js · Firebase",
        description: "A mobile-first calendar for field jobs, with a chat thread for each job.",
        overview: "Plan field jobs, invite the people working on them, and keep every message about a job in one thread.",
        contribution: "A private, custom-built app on Next.js and Firebase, made for use on a phone at the job site. Not public.",
        type: "web-app",
        mark: "JC",
        color: "#127A6F",
        status: "private",
        sort: 27,
        showOnHome: false,
        category: "management",
    },
    {
        // work in progress
        slug: "sheetcard",
        logo: "/projects/logos/sheetcard.png",
        title: "SheetCard",
        year: 2026,
        stack: ["React Native", "Expo"],
        stackShort: "Expo · iOS / Android",
        description: "A phone app that turns Excel and CSV files into searchable cards - on the device, no upload.",
        overview: "Open a spreadsheet on your phone and search it as a table or as cards.",
        contribution: "Building the iOS and Android app with Expo. Files stay on the device. Work in progress.",
        type: "mobile",
        mark: "SC",
        color: "#3F434A",
        status: "in-progress",
        sort: 28,
        showOnHome: false,
        category: "productivity",
    },
    {
        // closed
        slug: "king-of-the-world",
        logo: "/projects/logos/king-of-the-world.svg",
        title: "King of the World",
        year: 2026,
        stack: ["Next.js", "React", "Supabase", "Stripe"],
        stackShort: "Next.js · Supabase · Stripe",
        description: "A status game, an alternative to outbid.lol: players compete to hold the World title and one title per country. Closed.",
        overview: "A status game, an alternative to outbid.lol. Players collect in-app points to take a title, and it changes hands the moment someone passes the holder.",
        contribution: "Built the game, payments with Stripe and live standings with Supabase. Closed now.",
        type: "web-app",
        mark: "KW",
        color: "#B8860B",
        status: "closed",
        sort: 31,
        showOnHome: false,
        category: "other",
    },
    {
        slug: "search-favorite-movies",
        logo: "/projects/logos/search-favorite-movies.svg",
        title: "Search Favorite Movies",
        year: 2025,
        stack: ["React", "TypeScript"],
        stackShort: "React · TypeScript",
        description: "Search movies and save your favourites. A small React demo app.",
        overview: "Search a movie database and keep a list of favourites.",
        contribution: "A demo app in React and TypeScript.",
        type: "web-app",
        mark: "SM",
        color: "#7A5E6E",
        url: "https://search-favorite-movies.vercel.app",
        linkLabel: "See the demo",
        sort: 32,
        showOnHome: false,
        category: "demo",
    },
    {
        slug: "ideal-credit-npm",
        title: "ideal-credit (npm)",
        year: 2022,
        stack: ["JavaScript", "Vite"],
        stackShort: "JavaScript · npm",
        description: "Loan math for idealcredit.md: repayment schedules, the effective annual rate and debt-to-income checks.",
        overview:
            "A public npm package with the loan math behind idealcredit.md: repayment schedules, the effective annual interest rate (DAE) and debt-to-income checks.",
        contribution: "Wrote and publish the package. The website's loan calculators use it.",
        type: "package",
        logo: "/projects/logos/ideal-credit.svg",
        mark: "IC",
        color: "#127A6F",
        url: "https://www.npmjs.com/package/ideal-credit",
        linkLabel: "See on npm",
        sort: 33,
        showOnHome: false,
        category: "finance",
    },
    {
        slug: "1food-menu-npm",
        title: "1food-menu (npm)",
        year: 2022,
        stack: ["JavaScript", "CSS"],
        stackShort: "JavaScript · CSS · npm",
        description: "Digital menu templates for menus made with the 1FoodMenu app.",
        overview: "A public npm package with the JavaScript and CSS templates for menus made with the 1FoodMenu app.",
        contribution: "Wrote and published the package. Deprecated for now - new updates are coming soon.",
        type: "package",
        logo: "/projects/logos/1food-menu.svg",
        mark: "1F",
        color: "#16284D",
        url: "https://www.npmjs.com/package/1food-menu",
        linkLabel: "See on npm",
        status: "deprecated",
        sort: 34,
        showOnHome: false,
        category: "productivity",
    },

    // ── Udacity Front End course (2019) ──
    {
        slug: "landing-burger-max",
        title: "Burger Max landing page",
        year: 2019,
        stack: ["HTML", "CSS", "JavaScript"],
        stackShort: "HTML · CSS · JavaScript",
        description: "A restaurant landing page with a navigation menu built in plain JavaScript.",
        overview: "A one-page restaurant landing page. The navigation and the menu sections are generated from data with plain JavaScript, and the active section is highlighted as you scroll.",
        contribution: "Built during the Udacity Front End course.",
        type: "business-website",
        mark: "BM",
        color: "#A2471A",
        url: "https://nicojuhari.github.io/landing-burger-max/",
        linkLabel: "See the demo",
        sort: 40,
        showOnHome: false,
        category: "demo",
    },
    {
        slug: "travel-blog",
        title: "Travel Blog",
        year: 2019,
        stack: ["HTML", "CSS"],
        stackShort: "HTML · CSS",
        description: "A responsive blog layout in HTML and CSS.",
        overview: "A personal travel blog layout that works on phones, tablets and desktops.",
        contribution: "Built during the Udacity Front End course.",
        type: "business-website",
        mark: "TB",
        color: "#127A6F",
        url: "https://nicojuhari.github.io/travel-blog/",
        linkLabel: "See the demo",
        sort: 41,
        showOnHome: false,
        category: "demo",
    },
    {
        slug: "weather-journal",
        title: "Weather Journal",
        year: 2019,
        stack: ["JavaScript", "Node.js", "Express"],
        stackShort: "JavaScript · Node.js",
        description: "Enter a zip code and how you feel. The app adds the weather from an API and saves the entry.",
        overview: "A small journal app: you add a US zip code and a note, and it saves the entry with the current weather from the OpenWeatherMap API.",
        contribution: "Built during the Udacity Front End course, with a Node.js and Express server.",
        type: "web-app",
        mark: "WJ",
        color: "#1F4E9A",
        url: "https://github.com/nicojuhari/weather-journal",
        linkLabel: "See the code",
        sort: 42,
        showOnHome: false,
        category: "demo",
    },
    {
        slug: "natural-language-processing",
        title: "News Article Analysis",
        year: 2019,
        stack: ["JavaScript", "Node.js", "Express", "Webpack", "SASS", "Jest"],
        stackShort: "JavaScript · Node.js · Webpack",
        description: "Paste a news article link and see what a language API says about its tone.",
        overview: "Evaluate a news article with natural language processing. The Node.js server sends it to the Aylien text analysis API and the page shows the result.",
        contribution: "Built during the Udacity Front End course: Express server, Webpack dev and production builds, SASS and Jest tests.",
        type: "web-app",
        mark: "NL",
        color: "#7A5E6E",
        url: "https://github.com/nicojuhari/natural-language-processing",
        linkLabel: "See the code",
        sort: 43,
        showOnHome: false,
        category: "demo",
    },
];
